# Generated by Django 3.2 on 2022-10-21 16:11

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import event.lib
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_at', models.DateTimeField(default=event.lib.event_end_date, verbose_name='End Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Africa/Cairo', verbose_name='TimeZone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_event_by_me', related_query_name='event_events', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_event_by_me', related_query_name='event_events', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_at', models.DateTimeField(default=event.lib.event_category_end_date, verbose_name='End Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventcategory_by_me', related_query_name='event_eventcategorys', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventcategory_by_me', related_query_name='event_eventcategorys', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='event.event', verbose_name='Event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventcategory_by_me', related_query_name='event_eventcategorys', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventCustomer',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventcustomer_by_me', related_query_name='event_eventcustomers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventcustomer_by_me', related_query_name='event_eventcustomers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='event.event', verbose_name='Event')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPermission',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventpermission_by_me', related_query_name='event_eventpermissions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventpermission_by_me', related_query_name='event_eventpermissions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventpermission_by_me', related_query_name='event_eventpermissions', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSecurityLayer',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('level', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventsecuritylayer_by_me', related_query_name='event_eventsecuritylayers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventsecuritylayer_by_me', related_query_name='event_eventsecuritylayers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventteam_by_me', related_query_name='event_eventteams', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventteam_by_me', related_query_name='event_eventteams', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='event.event', verbose_name='Event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventteam_by_me', related_query_name='event_eventteams', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event.eventcategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventticket_by_me', related_query_name='event_eventtickets', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventticket_by_me', related_query_name='event_eventtickets', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='event.eventcustomer', verbose_name='Owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventticket_by_me', related_query_name='event_eventtickets', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('short', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_organizer_by_me', related_query_name='event_organizers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_organizer_by_me', related_query_name='event_organizers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('organizer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizing', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_organizer_by_me', related_query_name='event_organizers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityLayer',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_securitylayer_by_me', related_query_name='event_securitylayers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_securitylayer_by_me', related_query_name='event_securitylayers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.organizer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_securitylayer_by_me', related_query_name='event_securitylayers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slag', models.SlugField(max_length=150, unique=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='event.organizer', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCheck',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('checked_in', models.DateTimeField(blank=True, null=True)),
                ('checked_out', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_ticketcheck_by_me', related_query_name='event_ticketchecks', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_ticketcheck_by_me', related_query_name='event_ticketchecks', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='event.eventticket', verbose_name='Ticket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_ticketcheck_by_me', related_query_name='event_ticketchecks', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='event.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLayerMember',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_securitylayermember_by_me', related_query_name='event_securitylayermembers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_securitylayermember_by_me', related_query_name='event_securitylayermembers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_layers', to='event.teammember')),
                ('security_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_layer_members', to='event.securitylayer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_securitylayermember_by_me', related_query_name='event_securitylayermembers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTeamPermission',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventteampermission_by_me', related_query_name='event_eventteampermissions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventteampermission_by_me', related_query_name='event_eventteampermissions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='event.eventteam', verbose_name='Event Team')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_teams', to='event.eventpermission', verbose_name='Permission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventteampermission_by_me', related_query_name='event_eventteampermissions', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTeamMember',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventteammember_by_me', related_query_name='event_eventteammembers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventteammember_by_me', related_query_name='event_eventteammembers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='event.eventteam', verbose_name='Event Team')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_teams', to='event.teammember', verbose_name='Member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventteammember_by_me', related_query_name='event_eventteammembers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSecurityLayerMember',
            fields=[
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creted_event_eventsecuritylayermember_by_me', related_query_name='event_eventsecuritylayermembers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_eventsecuritylayermember_by_me', related_query_name='event_eventsecuritylayermembers', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('event_security_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='event.eventsecuritylayer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_security_layers', to='event.eventteammember')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventsecuritylayermember_by_me', related_query_name='event_eventsecuritylayermembers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventsecuritylayer',
            name='security_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.securitylayer'),
        ),
        migrations.AddField(
            model_name='eventsecuritylayer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventsecuritylayer_by_me', related_query_name='event_eventsecuritylayers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='eventcustomer',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='event.organizer', verbose_name='Organizer'),
        ),
        migrations.AddField(
            model_name='eventcustomer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_eventcustomer_by_me', related_query_name='event_eventcustomers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.organizer', verbose_name='Organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event_event_by_me', related_query_name='event_events', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
