# Generated by Django 3.2 on 2022-10-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_tickets_checks', to='event.eventsecuritylayermember', verbose_name='Checked by'),
        ),
    ]
