# Generated by Django 3.2 on 2022-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_ticketcheck_checked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcheck',
            options={'ordering': ['-checked_in', '-checked_out']},
        ),
        migrations.AddField(
            model_name='organizer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
